
name: code-check

on: [push, pull_request]

jobs:
  code-check:
    name: Mininet Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          # pylint 2.15 does not run on Python 3.12+
          python-version: "3.11"
      - name: Check out Mininet source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Mininet code check dependencies
        run: |
          PYTHON=`which python` util/install.sh -n
          python -m pip install pylint==2.15.7 pyflakes pycodestyle
      - name: Run code check
        run:  make codecheck
